export const SAVE_CLASSES = "SAVE_CLASSES";
export const FILTER_CLASSES = "FILTER_CLASSES";

export const SAVE_CALENDARS = "SAVE_CALENDARS";
export const SAVE_SECTIONS = "SAVE_SECTIONS";
export const CHANGE_CALENDAR = "CHANGE_CALENDAR";
